export const GRAPH_URL_MAINNET = process.env.NEXT_PUBLIC_GRAPH_ENDPOINT_MAINNET || ''
export const GRAPH_URL_KOVAN = process.env.NEXT_PUBLIC_GRAPH_ENDPOINT_KOVAN || ''
export const GRAPH_URL_GOERLI = process.env.NEXT_PUBLIC_GRAPH_ENDPOINT_GOERLI || ''
export const GRAPH_URL_OPTMISM = process.env.NEXT_PUBLIC_GRAPH_ENDPOINT_OPTIMISM || ''
